//USER ROLES ACTIONS
export const GET_LIST_DEPARTMENTS = "GET_LIST_DEPARTMENTS";
export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const CHANGE_VERIFICATION = "CHANGE_VERIFICATION";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";